In [82]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [102]:
data=pd.read_csv("dataset/train.csv")
data

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [84]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape



In [85]:
Y_train

array([5, 5, 6, ..., 7, 0, 6], dtype=int64)

In [86]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [108]:
# def init_params():
#     w1= np.random.rand(10,785) -0.5
#     b1=np.random.rand(10,1) -0.5
#     w2=np.random.rand(10,10) -0.5
#     b2=np.random.rand(10,1)- 0.5
#     return w1,b1,w2,b2

# def relu(z):
#     z=np.argmax(0,z)
#     return z

# def softmax(z):
#     z=np.exp(z)/sum(np.exp(z))
#     return z
# def forward_prop(w1,b1,w2,b2,X_train):
#     z1= w1.dot(X_train)+b1
#     A1=relu(z1)
#     z2=w2.dot(A1)+b2
#     A2= softmax(z2)
#     return z1,A1,z2,A2

# def ReLU_deriv(Z):
#     return Z > 0

# def one_hot(Y_train):
#     one_hot_Y = np.zeros((Y_train.size, Y_train.max() + 1))
#     one_hot_Y[np.arange(Y_train.size), Y_train] = 1
#     one_hot_Y = one_hot_Y.T
#     return one_hot_Y

# def backword_prop(Z1, A1, Z2, A2, W1, W2, X_train, Y_train):
#     one_hot_y= one_hot(Y_train)
#     dz2=A2-one_hot_y
#     dA1=W2.T.dot(dz2)
#     dz1=dA1*ReLU_deriv(Z1)
#     dw1= dz1.dot(X_train.T)
#     dw2=dz2.dot(A1.T)
#     db2=np.sum(dz2)
#     db1=np.sum(dz1)
#     return dw1,dw2,db1,db2

# def update_par(w1,w2,lr,dw1,dw2,db1,db2,b1,b2):
#     w1= w1-lr*(dw1)
#     w2= w1-lr*(dw2)
#     b1=b1-lr*(db1)
#     b2=b2-lr*(db2)
#     return w1,w2,b2,b1

    
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

# def backward_prop(Z1, A1, Z2, A2, W1, W2, X_train, Y_train):
#     one_hot_y= one_hot(Y_train)
#     dz2=A2-one_hot_y
#     dA1=W2.T.dot(dz2)
#     dz1=dA1*ReLU_deriv(Z1)
#     dw1= dz1.dot(X_train.T)
#     dw2=dz2.dot(A1.T)
#     db2=np.sum(dz2)
#     db1=np.sum(dz1)
#     return dw1,dw2,db1,db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2



In [88]:
# def gradient_descent1(X_train,Y_train,lr,iterations):
#     w1,b1,w2,b2= init_params()
#     for in range(iterations):
        

In [109]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y_train):
    print(predictions, Y_train)
    return np.sum(predictions == Y_train) / Y_train.size

def gradient_descent(X_train, Y_train, lr, iterations):
    w1, b1, w2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(w1, b1, w2, b2, X_train)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, w1, w2, X_train, Y_train)
        w1, b1, w2, b2 = update_params(w1, b1, w2, b2, dW1, db1, dW2, db2, lr)
        if i % 200 == 0:
             print("Iteration: ", i)
             predictions = get_predictions(A2)
             print(get_accuracy(predictions, Y_train))

    return w1, b1, w2, b2     

In [110]:
w1, b1, w2, b2 = gradient_descent(X_train, Y_train, 0.10, 1000)

Iteration:  0
[9 3 3 ... 3 3 3] [5 5 6 ... 7 0 6]
0.11339024390243903
Iteration:  200
[5 5 6 ... 7 5 2] [5 5 6 ... 7 0 6]
0.7581463414634146
